jdbldDirectory = _jdbld

extensionsSnapshotRepository = https://central.sonatype.com/repository/maven-snapshots/
buildExtensions =  \
    org.jdrupes.gitversioning:core:0.1.1,\
    org.jdrupes:jdbld-ext-bnd:0.0.23

javaHome = /usr/lib/jvm/java-25
