jdbldDirectory = _jdbld

extensionsSnapshotRepository = https://central.sonatype.com/repository/maven-snapshots/
# buildExtensions = org.eclipse.jgit:org.eclipse.jgit:7.3.0.202506031305-r
buildExtensions =  \
    org.jdrupes.gitversioning:core:0.1.1

javaHome = /usr/lib/jvm/java-25
