jdbldDirectory = _jdbld

extensionsSnapshotRepository = https://central.sonatype.com/repository/maven-snapshots/
buildExtensions =  \
    org.jdrupes:jdbld-ext-git:0.10.0,\
    org.jdrupes:jdbld-ext-bnd:0.7.0

javaHome = /usr/lib/jvm/java-25
