<div class="HelloWorld-view" data-portletTitle="Hello World">
    <div style="font-size: 400%">Hello World! 
        <img class="helloWorldIcon" style='vertical-align: bottom;'
            src="${portletResource('globe#1.ico')}">
        <!-- World icon from http://apathae.deviantart.com/ -->
    </div>
    <div>
        <button class="HelloWorld-toggle ui-button ui-widget ui-corner-all">Toggle World</button>
    </div>
</div>