/*
 * JGrapes Event Driven Framework
 * Copyright (C) 2016  Michael N. Lipp
 * 
 * This program is free software; you can redistribute it and/or modify it 
 * under the terms of the GNU General Public License as published by 
 * the Free Software Foundation; either version 3 of the License, or 
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful, but 
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License 
 * for more details.
 * 
 * You should have received a copy of the GNU General Public License along 
 * with this program; if not, see <http://www.gnu.org/licenses/>.
 */
package org.jdrupes.httpcodec;

import java.nio.Buffer;
import java.nio.ByteBuffer;
import java.util.Optional;

/**
 * An engine that can be used as a server. It has an associated
 * request decoder and response encoder.
 * 
 * @param <Q> the message header type handled by the decoder (the request)
 * @param <R> the message header type handled be the encoder (the response)
 * 
 * @author Michael N. Lipp
 */
public class ServerEngine<Q extends MessageHeader, R extends MessageHeader>
	extends Engine<Q, R> {

	private RequestDecoder<?, ?> requestDecoder;
	private ResponseEncoder<?> responseEncoder;
	
	/**
	 * Creates a new instance.
	 * 
	 * @param requestDecoder the decoder for the request
	 * @param responseEncoder the encoder for the response
	 */
	@SuppressWarnings("unchecked")
	public ServerEngine	(RequestDecoder<Q, R> requestDecoder, 
				ResponseEncoder<R> responseEncoder) {
		this.requestDecoder = (RequestDecoder<MessageHeader, MessageHeader>)
				requestDecoder;
		this.responseEncoder = (ResponseEncoder<MessageHeader>)responseEncoder;
	}

	/**
	 * Returns the request decoder.
	 * 
	 * @return the request decoder
	 */
	@SuppressWarnings("unchecked")
	public RequestDecoder<Q, R> requestDecoder() {
		return (RequestDecoder<Q, R>)requestDecoder;
	}

	/**
	 * Returns the response encoder.
	 * 
	 * @return the response encoder
	 */
	@SuppressWarnings("unchecked")
	public ResponseEncoder<R> responseEncoder() {
		return (ResponseEncoder<R>)responseEncoder;
	}

	/**
	 * Decodes a request sent to the server.
	 * 
	 * @param in the data to decode
	 * @param out the decoded data
	 * @param endOfInput {@code true} if this invocation finishes the message
	 * @return the result
	 * @throws ProtocolException if the input violates the protocol
	 */
	@SuppressWarnings("unchecked")
	public RequestDecoder.Result<R> decode
		(ByteBuffer in, Buffer out, boolean endOfInput)
			throws ProtocolException {
		return (RequestDecoder.Result<R>)
				requestDecoder.decode(in, out, endOfInput);
	}

	/**
	 * Encodes a response generated by the server. This method may
	 * cause a switch of the protocol if the response is a HTTP
	 * "switch protocol" response.
	 * 
	 * @param messageHeader the message header
	 * @see ResponseEncoder#encode(MessageHeader)
	 */
	@SuppressWarnings("unchecked")
	public void encode(R messageHeader) {
		((ResponseEncoder<R>)responseEncoder).encode(messageHeader);
	}

	/**
	 * Invokes the encoder's encode method. This method must be used
	 * instead of decoding the encoder's method directly if the
	 * encoder and decoder should adapt to a protocol
	 * switch automatically.
	 * 
	 * @param out the decoded data
	 * @return the result
	 * @see ResponseEncoder#encode(ByteBuffer)
	 */
	public ResponseEncoder.Result encode(
	        ByteBuffer out) {
		return encode(Codec.EMPTY_IN, out, true);
	}

	/**
	 * Invokes the encoder's encode method. This method must be used
	 * instead of decoding the encoder's method directly if the
	 * encoder and decoder should adapt to a protocol
	 * switch automatically.
	 * 
	 * @param in the data to encode
	 * @param out the encoded data
	 * @param endOfInput {@code true} if this invocation finishes the message
	 * @return the result
	 * @see ResponseEncoder#encode(Buffer, ByteBuffer, boolean)
	 */
	public ResponseEncoder.Result encode(
	        Buffer in, ByteBuffer out, boolean endOfInput) {
		ResponseEncoder.Result result = responseEncoder.encode(in, out, endOfInput);
		if (result.newProtocol() != null) {
			requestDecoder = result.newDecoder();
			responseEncoder = result.newEncoder();
		}
		return result;
	}

	/**
	 * Returns the last fully decoded request if it exists.
	 * 
	 * @return the request
	 */
	@SuppressWarnings("unchecked")
	public Optional<Q> currentRequest() {
		return (Optional<Q>)requestDecoder.getHeader();
	}
	
}
