<div class="HelloWorld-view" data-portlet-title="${_("portletName")}">
    <div style="font-size: 400%">${_("HelloWorld")} 
        <img class="helloWorldIcon" style='vertical-align: bottom;'
            src="${portletResource('globe.ico')}">
        <!-- World icon from http://apathae.deviantart.com/ -->
    </div>
    <div>
        <button class="HelloWorld-toggle ui-button ui-widget ui-corner-all">${_("ToggleWorld")}</button>
    </div>
</div>