name: Java CI

on: [push]

concurrency:
  group: doc_generation
  cancel-in-progress: false

jobs:
  build:
    strategy:
      matrix:
        java-version: [ '21' ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Java 25 for jdbld
        run: sudo apt-get install openjdk-25-jre
      - name: Install graphviz
        run: sudo apt-get install graphviz
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'adopt'
      - name: check
        run: update-alternatives --list java
      - name: Build with jdbld
        run: JAVA_HOME=/usr/lib/jvm/java-25-openjdk-amd64/ ./jdbld -Prepo.access.token=${{ secrets.REPO_ACCESS_TOKEN }} stage
